
version: '2.1'

services:
  swagger:
    image:
      swaggerapi/swagger-ui:v3.23.5
    ports:
      - 3000:8080
    environment:
      - SWAGGER_JSON=/api.yml
    volumes:
      - ../api.yml:/api.yml:ro